name: Build macOS Universal Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin,aarch64-apple-darwin
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Install frontend dependencies
      run: bun install
    
    - name: Build universal binary
      run: bun run tauri build --target universal-apple-darwin
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: claudia-macos-universal
        path: |
          src-tauri/target/release/bundle/dmg/*.dmg
          src-tauri/target/release/bundle/macos/*.app
        if-no-files-found: error